apiVersion: batch/v1
kind: Job
metadata:
  name: "otus"
spec:
  template:
    metadata:
      name: "otus"
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: postgres:latest
        env:
          - name: POSTGRES_PASSWORD
            value: "qwerty"
        command:
          - sh
          - "-c"
          - |
            psql postgres://arslanov:qwerty@postgres-service/test <<'EOF'
              create table client (id serial primary key, firstname varchar, lastname varchar);
                insert into client (firstname, lastname) values ('Konstantin', 'Kolyshkov');
            EOF

  backoffLimit: 0

