apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: otus-rs
  labels:
    app: otus
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: otus
  template:
    metadata:
      labels:
        app: otus
    spec:
      containers:
        - name: otus
          image: arslanov92/otus_homework:0.0.9