# Forked from https://github.com/reproducible-containers/repro-get/blob/v0.2.1/.github/workflows/release.yml
# Forked from https://github.com/containerd/nerdctl/blob/v0.8.1/.github/workflows/release.yml
# Apache License 2.0

name: Release
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
jobs:
  release:
    runs-on: macos-11
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with:
          # https://github.com/reproducible-containers/repro-get/issues/3
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: "Install dependencies"
        # coreutils:  For `gtouch -d @${SOURCE_DATE_EPOCH}`
        # diffoscope: For `make test.repro`
        run: brew install coreutils diffoscope
      - name: "Test reproducibility"
        run: |
          make test.repro
          git clean -xfd
      - name: "Make artifacts"
        run: make artifacts
      - name: "SHA256SUMS"
        run: |
          cat _artifacts/SHA256SUMS
      - name: "The sha256sum of the SHA256SUMS file"
        run: |
          (cd _artifacts; shasum -a 256 SHA256SUMS)
      - name: "Prepare the release note"
        run: |
          shasha=$(shasum -a 256 _artifacts/SHA256SUMS | awk '{print $1}')
          cat <<-EOF | tee /tmp/release-note.txt
          (Changes to be documented)
          - - -
          The binaries were built automatically on GitHub Actions.
          The build log is available for 90 days: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

          The sha256sum of the SHA256SUMS file itself is \`${shasha}\` .
          EOF
      - name: "Create release"
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF##*/}"
          gh release create -F /tmp/release-note.txt --draft --title "${tag}" "${tag}" _artifacts/*
